# Container image that runs your code
FROM ubuntu:latest

# Copies your code file from your action repository to the filesystem path `/` of the container
COPY target/release/aggregation /usr/local/bin
COPY continuous/tool /var/tool

RUN apt update && apt install sqlite3 ca-certificates -y && update-ca-certificates

# should map your .env to /app/.env
WORKDIR /app

# Execute when the docker container starts up (`entrypoint.sh`)
ENTRYPOINT ["aggregation"]
