version: '3.8'

services:
  relayer:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: relayer
    volumes:
      - ./relayer:/var/data
      - ./relayer/.env:/app/.env
    ports:
      - "8900:9100"
      - "8443:8443"
    env_file:
      - ./relayer/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8900"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 5s

  challenger_0:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: challenger_0
    volumes:
      - ./challenge_0:/var/data
      - ./challenge_0/.env:/app/.env
    ports:
      - "8901:9100"
      - "8451:8443"
    env_file:
      - ./challenge_0/.env
    restart: unless-stopped
    depends_on:
      relayer:
        condition: service_healthy

  operator_0:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: operator_0
    volumes:
      - ./operator_0:/var/data
      - ./operator_0/.env:/app/.env
    ports:
      - "8902:9100"
      - "8452:8443"
    env_file:
      - ./operator_0/.env
    restart: unless-stopped
    depends_on:
      relayer:
        condition: service_healthy

  operator_1:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: operator_1
    volumes:
      - ./operator_1:/var/data
      - ./operator_1/.env:/app/.env
    ports:
      - "8903:9100"
      - "8453:8443"
    env_file:
      - ./operator_1/.env
    restart: unless-stopped
    depends_on:
      relayer:
        condition: service_healthy

  committee_0:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: committee_0
    volumes:
      - ./commitee_0:/var/data
      - ./commitee_0/.env:/app/.env
    ports:
      - "8904:9100"
      - "8454:8443"
    env_file:
      - ./commitee_0/.env
    restart: unless-stopped
    depends_on:
      relayer:
        condition: service_healthy

  committee_1:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: committee_1
    volumes:
      - ./commitee_1:/var/data
      - ./commitee_1/.env:/app/.env
    ports:
      - "8905:9100"
      - "8455:8443"
    env_file:
      - ./commitee_1/.env
    restart: unless-stopped
    depends_on:
      relayer:
        condition: service_healthy




