version: '3.8'

services:

  committee_0:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: committee_0
    volumes:
      - ./committee_0:/var/data
      - ./committee_0/.env:/app/.env
    ports:
      - "8900:9100"
      - "8443:8443"
    env_file:
      - ./committee_0/.env
    restart: unless-stopped

  committee_1:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: committee_1
    volumes:
      - ./committee_1:/var/data
      - ./committee_1/.env:/app/.env
    ports:
      - "8901:9100"
      - "8444:8443"
    env_file:
      - ./committee_1/.env
    restart: unless-stopped
    depends_on:
      - committee_0

  challenger_0:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: challenger_0
    volumes:
      - ./challenger_0:/var/data
      - ./challenger_0/.env:/app/.env
    ports:
      - "8902:9100"
      - "8445:8443"
    env_file:
      - ./challenger_0/.env
    restart: unless-stopped
    depends_on:
      - committee_0

  operator_0:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: operator_0
    volumes:
      - ./operator_0:/var/data
      - ./operator_0/.env:/app/.env
    ports:
      - "8903:9100"
      - "8456:8443"
    env_file:
      - ./operator_0/.env
    restart: unless-stopped
    depends_on:
      - committee_0

  watchtower_0:
    image: ghcr.io/goatnetwork/bitvm2-node:${TAG:-0.1.0}
    container_name: watchtower_0
    volumes:
      - ./watchtower_0:/var/data
      - ./watchtower_0/.env:/app/.env
    ports:
      - "8904:9100"
      - "8457:8443"
    env_file:
      - ./watchtower_0/.env
    restart: unless-stopped
    depends_on:
      - committee_0