[package]
name = "cbft-rpc"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }

bitcoin-light-client-circuit = { workspace = true }
state-chain = { workspace = true }
commit-chain = { workspace = true }

tendermint = { workspace = true, default-features = false, features = ["secp256k1"] }
tendermint-light-client-verifier = { workspace = true, default-features = false, features = [
  "rust-crypto",
] }
anyhow = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true