[package]
name = "header-chain"
version.workspace = true
edition.workspace = true
#resolver.workspace = true

[dependencies]
borsh = {version = "1.5.3", features = ["derive"] }
sha2 =  { version = "0.10.9", default-features = false }
bitcoin = { workspace = true, features = ["serde", "rand", "secp-recovery"] }
serde = { workspace = true, default-features = false }
crypto-bigint = { version = "0.5.5", default-features = false }
zkm-zkvm = { git = "https://github.com/ProjectZKM/Ziren", package = "zkm-zkvm", features = ["verify"] }
zkm-verifier = { git = "https://github.com/ProjectZKM/Ziren", package = "zkm-verifier" }

[dev-dependencies]
hex-literal = "1.0.0"