[package]
name = "bitvm2-noded"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bitvm2-noded"
path = "src/main.rs"

[[bin]]
name = "sequencer-set-publish"
path = "src/bin/sequencer-set-publish.rs"

[[bin]]
name = "event_tool"
path = "src/bin/event_tool.rs"

[dependencies]
libp2p = { workspace = true, features = [
    "autonat",
    "dns",
    "tokio",
    "noise",
    "tcp",
    "yamux",
    "identify",
    "kad",
    "ping",
    "relay",
    "metrics",
    "rsa",
    "macros",
    "gossipsub",
    "quic",
    "websocket",
] }
libp2p-swarm-derive = { workspace = true }
libp2p-metrics = { workspace = true }
futures = { workspace = true }

bitvm2-lib = { workspace = true }
store = { workspace = true }
client = { workspace = true }
bitcoin-light-client-circuit = { workspace = true }
commit-chain = { workspace = true }

clap = { workspace = true }
zeroize = { workspace = true }
axum = { workspace = true, features = ["macros", "json"] }
http-body-util = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
reqwest = { version = "0.12.15", features = ["json"] }

prometheus-client = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
http = "1.3.1"
rand = "0.8.5"
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
base64 = "0.22.1"
anyhow = { workspace = true }
thiserror = "2.0"
musig2 = { version = "0.1.0", features = ["serde", "rand"] }
esplora-client = { workspace = true }
bitvm = { workspace = true }
bitcoin = { workspace = true }

goat = { workspace = true }
uuid = { workspace = true }
hex = { workspace = true }
alloy = { workspace = true, features = ["full", "serde"] }
secp256k1 = { workspace = true }
sha2 = { workspace = true }
dotenv = { workspace = true }

bincode = "1.3.3"
bitcoin-script = { workspace = true }
once_cell = { workspace = true }
ark-bn254 = { workspace = true }
ark-groth16 = { workspace = true }
ark-serialize = { workspace = true }
async-trait = { workspace = true }

zkm-sdk = { workspace = true }
zkm-verifier = { workspace = true }

stun-client = "0.1.4"
strum = { version = "0.26", features = ["derive"] }
borsh = {version = "1.5.3", features = ["derive"] }
commit-chain-rpc = { workspace = true }

# bin
tempfile = "3.19.1"
proofs = { path = "../crates/proofs" }
tokio-util = "0.7.15"

[features]
default = []
tests = []
e2e-tests = []
