name: Release

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: ${{ matrix.target }}
    needs:
      - create-release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      # Install Go for all platforms (required for zkm-recursion-gnark-ffi)
      - name: Install Go (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Go (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install Go (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      # Install protobuf-compiler for Ubuntu
      - name: Install protobuf-compiler (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      # Install protobuf-compiler for macOS
      - name: Install protobuf-compiler (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install protobuf
      # Install protobuf-compiler for Windows
      - name: Install protobuf-compiler (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install protoc
      # Install MSVC Tools (Windows)
      - name: Setup MSVC (Windows)
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.3.1
      # Install Rust nightly toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      # Set Windows environment variables for linking
      - name: Set Windows Environment (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER=link.exe" >> $env:GITHUB_ENV
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $env:GITHUB_ENV
          # Install Windows network libraries for pnet
          choco install npcap
          # Set pnet library path
          echo "PNET_LIB_PATH=C:\Program Files\Npcap\Lib\x64" >> $env:GITHUB_ENV
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required)
          bin: bitvm2-noded
          archive: $bin-$target
          target: ${{ matrix.target }}
          tar: all
          manifest-path: node/Cargo.toml
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_PROFILE_RELEASE_LTO: true
          # Windows specific settings
          RUSTFLAGS: ${{ matrix.os == 'windows-latest' && '-C target-feature=+crt-static' || '' }}
          # Windows network library path for pnet
          PNET_LIB_PATH: ${{ matrix.os == 'windows-latest' && 'C:\Program Files\Npcap\Lib\x64' || '' }}
