name: Release

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: ${{ matrix.target }}
    needs:
      - create-release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      # Install protobuf-compiler for Ubuntu
      - name: Install protobuf-compiler (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      # Install protobuf-compiler for macOS
      - name: Install protobuf-compiler (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install protobuf
      # Install protobuf-compiler for Windows
      - name: Install protobuf-compiler (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install protoc
      # Install Rust nightly toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required)
          bin: bitvm2-noded
          archive: $bin-$target
          target: ${{ matrix.target }}
          tar: all
          manifest-path: node/Cargo.toml
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_PROFILE_RELEASE_LTO: true
